### ISSUE TITLE
Error when running on empty glyphs

### ISSUE THREAD

**Issue by mekkablue** [slobzheninov/GreenHarmony#1]
1. select empty glyph (e.g. space) in Font view (Cmd-Opt-1)
2. run _Filter > Green Harmony_

Error:

```
<class 'TypeError'>: runFilterWithLayers:error:: Need tuple of 2 arguments as result
```

**Comment by slobzheninov** [comment]
Fixed!

**Comment by mekkablue** [comment]
Thanks! I updated the version info accordingly:
Commit 1e0669555ed0937bd5fc3e6c4eb804c5c9c64e13
